

###
POST http://localhost:4000/user/register
Content-Type: application/json

{
    "userName": "Jim",
    "email": "ImJim93@gmail.com",
    "password": "ImJim12345",
    "limit": 5
}

###
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "userName": "Jim",
    "email": "ImJim93@gmail.com",
    "password": "ImJim12345"
}


###
POST http://localhost:4000/user/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjg2MjIwNTEwLCJleHAiOjE2ODYyMjE0MTB9.ag3mVzxbq7_aBTdy10I_aFGSJvLv9Hw54-dAS64rjSs"
}








// ---> CARDS SECTION <--------------------------------------------------------------

###
GET http://localhost:4000/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODQ5YTIzNDE1NDcyMzEyMmRiNjZlYiIsInVzZXJOYW1lIjoiSmltIiwibGltaXQiOjUsImVtYWlsIjoiSW1KaW05M0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRvL2ZsYi9lWGhmOEZSd0lwWG8xd3hPbnVVZkxyRFR4bnBFTS9FMXNydkZ3SzA5L0YxdFFYNiIsIl9fdiI6MH0sImlhdCI6MTY4NjQxMTk5OCwiZXhwIjoxNjg2NDE1NTk4fQ.IPAWDSD1WaArZWS620Xu77M33FlEKBpF7b5iozUHJ9k


###
POST http://localhost:4000/cards/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODQ5YTIzNDE1NDcyMzEyMmRiNjZlYiIsInVzZXJOYW1lIjoiSmltIiwibGltaXQiOjUsImVtYWlsIjoiSW1KaW05M0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRvL2ZsYi9lWGhmOEZSd0lwWG8xd3hPbnVVZkxyRFR4bnBFTS9FMXNydkZ3SzA5L0YxdFFYNiIsIl9fdiI6MH0sImlhdCI6MTY4NjQxMTk5OCwiZXhwIjoxNjg2NDE1NTk4fQ.IPAWDSD1WaArZWS620Xu77M33FlEKBpF7b5iozUHJ9k

{
    "word": "wor22",
    "translate": "só222"
}

###
GET http://localhost:4000/cards/single/64842cf058d5d31f08d9ab12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODFhODlhNWZiY2I4ZGQxYThmZjhjYiIsInVzZXJOYW1lIjoiSmltIiwiZW1haWwiOiJJbUppbTkzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEpja2kzbUR5TlVvVlg2amdrY0h6S09MeE8vMTI5VlI2Ukx2UTJwdkpVYUpJc0p1LkJwQkFpIiwiX192IjowfSwiaWF0IjoxNjg2Mzg1ODc4LCJleHAiOjE2ODYzODk0Nzh9.9nE_mOVXkPeAdnR0pn7-DiZHjdja7ok1t0DsXWSQGl0


###
POST http://localhost:4000/cards/compare/64845d71f8b44c5288c9296d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODFhODlhNWZiY2I4ZGQxYThmZjhjYiIsInVzZXJOYW1lIjoiSmltIiwiZW1haWwiOiJJbUppbTkzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEpja2kzbUR5TlVvVlg2amdrY0h6S09MeE8vMTI5VlI2Ukx2UTJwdkpVYUpJc0p1LkJwQkFpIiwiX192IjowfSwiaWF0IjoxNjg2Mzk1MDcwLCJleHAiOjE2ODYzOTg2NzB9.oKIXZ8jTqfSIH2-HEThG5RQY7Y3uPfpuPbqOuqObmt4


{
    "translate": "szó5"
}




