// ---> CARDS SECTION <--------------------------------------------------------------

###
GET http://localhost:8080/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODVlY2E5ZWNiMzJmMmEyY2E5OWNlYiIsInVzZXJOYW1lIjoiQmFybGV5IiwibGltaXQiOjUsImVtYWlsIjoiZGV2ZWxvcGVkYnliYXJsZXlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZWdjUHhnZnYvYVhIZE4xREREd1NzLkVYZ3RxTUJkUGhFYVduazBmRnd3c1ZRR1htSFE3WEciLCJfX3YiOjB9LCJpYXQiOjE2ODY3NTI1MzAsImV4cCI6MTY4Njc1MzEzMH0.smgvZas5k2M2ad7ddLtlA3Svo0fhMbtgSD3Wu8U0a5I

###
GET http://localhost:8080/cards/648605e924c2a558b5341575
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODVlY2E5ZWNiMzJmMmEyY2E5OWNlYiIsInVzZXJOYW1lIjoiQmFybGV5IiwibGltaXQiOjUsImVtYWlsIjoiZGV2ZWxvcGVkYnliYXJsZXlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZWdjUHhnZnYvYVhIZE4xREREd1NzLkVYZ3RxTUJkUGhFYVduazBmRnd3c1ZRR1htSFE3WEciLCJfX3YiOjB9LCJpYXQiOjE2ODY3NTI1MzAsImV4cCI6MTY4Njc1MzEzMH0.smgvZas5k2M2ad7ddLtlA3Svo0fhMbtgSD3Wu8U0a5I

###
POST http://localhost:8080/cards/new/648994a56ea60a3413430539
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODVlY2E5ZWNiMzJmMmEyY2E5OWNlYiIsInVzZXJOYW1lIjoiQmFybGV5IiwibGltaXQiOjUsImVtYWlsIjoiZGV2ZWxvcGVkYnliYXJsZXlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZWdjUHhnZnYvYVhIZE4xREREd1NzLkVYZ3RxTUJkUGhFYVduazBmRnd3c1ZRR1htSFE3WEciLCJfX3YiOjB9LCJpYXQiOjE2ODY3NTI1MzAsImV4cCI6MTY4Njc1MzEzMH0.smgvZas5k2M2ad7ddLtlA3Svo0fhMbtgSD3Wu8U0a5I

{
    "word": "wor222",
    "translate": "só2222"
}

###
GET http://localhost:8080/cards/single/6485df160cccb5ad1afded65
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODU4OGI4NGI2YTA5MTlmMzVkNjU4OCIsInVzZXJOYW1lIjoiQmFybGV5IiwibGltaXQiOjMsImVtYWlsIjoiZGV2ZWxvcGVkYnliYXJsZXlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkSkF6NUM3OTJyNWltdTVsejg0NEN2LnVtcFRNdUFnM05Gb2QyMjY2bUlTcnM1bHdEWEF1RUciLCJfX3YiOjB9LCJpYXQiOjE2ODY0OTQ0NjAsImV4cCI6MTY4NjQ5NjI2MH0.w9uPqP9QMl9yC2ZKxBA_BQ3Y0x6OPW4c1duK1e0SHAY



###
POST http://localhost:8080/cards/compare/6486396de7569b7d6240e1bf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0ODVlY2E5ZWNiMzJmMmEyY2E5OWNlYiIsInVzZXJOYW1lIjoiQmFybGV5IiwibGltaXQiOjUsImVtYWlsIjoiZGV2ZWxvcGVkYnliYXJsZXlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZWdjUHhnZnYvYVhIZE4xREREd1NzLkVYZ3RxTUJkUGhFYVduazBmRnd3c1ZRR1htSFE3WEciLCJfX3YiOjB9LCJpYXQiOjE2ODY1MTc5MDcsImV4cCI6MTY4NjUxODUwN30.hMfT3y3zCV-a4MBOLLi-fYP64Qh5KsaM_RRFD2vwqbI

{
    "translate": "só2222"
}